name: Python Security

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  python-security:
    name: Python Security Check
    uses: ./.github/workflows/reusable-py-security.yml
    with:
      python-version: "3.13"
      bandit-target: "python_template_base"
