name: Secret Scan

on:
  pull_request:
  push:
    branches: [main]

jobs:
  secret-scan:
    name: Secret Scan
    uses: y-maeda1116/security-base/.github/workflows/reusable-secret-scan.yml@main
    with:
      scan-tool: "trivy"
