name: Secret Scan

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  secret-scan:
    name: Secret Scan
    uses: ./.github/workflows/reusable-secret-scan.yml
    with:
      scan-tool: "trivy"
